In [38]:
# Data Cleaning: World Population Dataset

#Dataset: Population – UN World Population Prospects
#Source: Our World in Data / United Nations World Population Prospects 2024

In [39]:
import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

Saving population-unwpp.csv to population-unwpp (6).csv

In [40]:
df = pd.read_csv("population-unwpp.csv")

# Keep a copy of the original dataset
raw_df = df.copy()

df.head()

        Entity Code  Year  Population (historical estimates)
0  Afghanistan  AFG  1950                            7776180
1  Afghanistan  AFG  1951                            7879343
2  Afghanistan  AFG  1952                            7987784
3  Afghanistan  AFG  1953                            8096703
4  Afghanistan  AFG  1954                            8207954

In [41]:
print("===== FINAL DATA QUALITY CHECK =====")

print("Missing values:")
print(cleaned_df.isnull().sum())

print("\nDuplicate rows:")
print(cleaned_df.duplicated().sum())

print("\nNegative population values:")
print(
    (cleaned_df["Population (historical estimates)"] < 0).sum()
)

print("\nYear range:")
print(
    cleaned_df["Year"].min(),
    "to",
    cleaned_df["Year"].max()
)

print("\nFinal shape:")
print(cleaned_df.shape)

===== FINAL DATA QUALITY CHECK =====
Missing values:
Entity                               0
Code                                 0
Year                                 0
Population (historical estimates)    0
dtype: int64

Duplicate rows:
0

Negative population values:
0

Year range:
1950 to 2023

Final shape:
(19388, 4)

In [42]:
print("Missing Code values:",
      df["Code"].isna().sum())

print("\nCode length counts:")
print(df["Code"].dropna().str.len().value_counts())

Q1 = df["Population (historical estimates)"].quantile(0.25)
Q3 = df["Population (historical estimates)"].quantile(0.75)
IQR = Q3 - Q1

upper_bound = Q3 + 1.5 * IQR

outliers = df[
    df["Population (historical estimates)"] > upper_bound
]

print("\nPotential population outliers:", len(outliers))

print("\nNegative population values:",
      (df["Population (historical estimates)"] < 0).sum())

print("Duplicate Entity-Year records:",
      df.duplicated(subset=["Entity", "Year"]).sum())

Missing Code values: 592

Code length counts:
Code
3    17464
8      888
6      444
Name: count, dtype: int64

Potential population outliers: 3061

Negative population values: 0
Duplicate Entity-Year records: 0

In [43]:
cleaned_df = df.copy()

cleaned_df["Entity"] = cleaned_df["Entity"].str.strip()

cleaned_df["Code"] = cleaned_df["Code"].fillna("N/A")
cleaned_df["Code"] = cleaned_df["Code"].astype(str).str.strip()

cleaned_df = cleaned_df.drop_duplicates()

cleaned_df["Year"] = pd.to_numeric(
    cleaned_df["Year"],
    errors="coerce"
)

cleaned_df["Population (historical estimates)"] = pd.to_numeric(
    cleaned_df["Population (historical estimates)"],
    errors="coerce"
)

print("Cleaning completed!")

Cleaning completed!

In [44]:
print("Original shape:", raw_df.shape)
print("Cleaned shape:", cleaned_df.shape)

print("\nMissing values after cleaning:")
print(cleaned_df.isnull().sum())

print("\nDuplicate rows after cleaning:",
      cleaned_df.duplicated().sum())

print("\nFirst 5 cleaned records:")
display(cleaned_df.head())

Original shape: (19388, 4)
Cleaned shape: (19388, 4)

Missing values after cleaning:
Entity                               0
Code                                 0
Year                                 0
Population (historical estimates)    0
dtype: int64

Duplicate rows after cleaning: 0

First 5 cleaned records:

        Entity Code  Year  Population (historical estimates)
0  Afghanistan  AFG  1950                            7776180
1  Afghanistan  AFG  1951                            7879343
2  Afghanistan  AFG  1952                            7987784
3  Afghanistan  AFG  1953                            8096703
4  Afghanistan  AFG  1954                            8207954

In [45]:
cleaned_df.to_csv("cleaned_data.csv", index=False)

print("cleaned_data.csv created successfully!")

cleaned_data.csv created successfully!

In [46]:
print("Sample codes:")
print(df["Code"].dropna().unique()[:30])

invalid_code_length = df[
    df["Code"].notna() &
    (df["Code"].str.len() != 3)
]

print("Codes that are not 3 characters:",
      len(invalid_code_length))

Sample codes:
['AFG' 'OWID_AFR' 'UN_AFR' 'ALB' 'DZA' 'ASM' 'AND' 'AGO' 'AIA' 'ATG' 'ARG'
 'ARM' 'ABW' 'OWID_ASI' 'UN_ASI' 'AUS' 'AUT' 'AZE' 'BHS' 'BHR' 'BGD' 'BRB'
 'BLR' 'BEL' 'BLZ' 'BEN' 'BMU' 'BTN' 'BOL' 'BES']
Codes that are not 3 characters: 1332

In [47]:
cleaned_df.to_csv("cleaned_data.csv", index=False)
from google.colab import files

files.download("cleaned_data.csv")